config/routes.rb
Rails.application.routes.draw do
    resources :accounts, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
        get :password, :on => :member
        patch :password, :on => :member, :action => :passwordupdate
    end
    resources :groups do
        get :delete, :on => :member
    end

    resources :aliases, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
    end

    resource :profile do
        get :password
        patch :password, :action => :passwordupdate
        get 'group/:id' => 'profiles#group', as: 'group'
        get 'group/:id/leave' => 'profiles#groupleave', as: 'groupleave'
        delete 'group/:id/leave' => 'profiles#groupleft', as: 'groupleft'
    end

    get '/', :to => 'profiles#index'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
    before_filter :authorizeadmin

    def index
        @aliases = Alias.all(:limit => 50, :offset => params[:count].to_i, :sort_by => 'uid')
    end

    def new
        @alias = Alias.new
    end

    def create
        @alias = Alias.new(alias_params)
        @alias.forwardTo = Account.find(alias_params[:forwardTo]).dn
        begin
            if @alias.save
                redirect_to @alias
            else
                render 'new'
            end
        rescue ActiveLdap::LdapError::InsufficientAccess
            redirect_to aliases_path, alert: "Insufficient Access!"
        rescue ActiveLdap::LdapError::ConstraintViolation
            redirect_to aliases_path, alert: "Alias UIDs must be #{UIDCONST} and unique"
        end
    end

    def show
        begin
            @alias = Alias.find(params[:id], :attributes => ["+", "*"])
        rescue ActiveLdap::EntryNotFound
            redirect_to aliases_path, alert: "Alias #{params[:id]} not found." and return
        end
        render 'alias'
    end

    def delete
        @alias = Alias.find(params[:id])
    end

    def destroy
        Alias.destroy(params[:id])
        redirect_to aliases_path, notice: "Alias #{params[:id]} deleted."
    end


    private
    def alias_params
        params.require(:alias).permit(:uid, :forwardTo)
    end

end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/views/aliases/delete.html.erb
<%= form_for(@alias, :url => { :action => :destroy }, :html => { :method => :delete }) do |f| %>
    <%= render partial: 'sign', locals: {type: 'danger', text: "Are you sure you want to delete the alias '#{@alias.uid}'?" } %>
    <%= link_to 'No', :back, class: "btn btn-lg btn-primary" %>
    <%= f.submit value: "Yes »", class: "btn btn-lg btn-danger" %>
<% end %>

app/views/aliases/index.html.erb
<table class="table table-striped">
<tr>
    <th>UID</th>
    <th>To</th>
</tr>
<% @aliases.each do |a| %>
    <% forwardTo = Account.find(a.forwardTo).uid %>
    <tr>
    <td><%= link_to a.uid, a, title: a.uid %></td>
    <td><%= link_to forwardTo, account_path(forwardTo), title: forwardTo %></td>
    </tr>
<% end %>
</table>
<%= link_to 'New Alias', new_alias_path, class: "btn btn-lg btn-primary btn-success" %>

app/views/aliases/new.html.erb
<% if @alias.errors.any? %>
    <%= render partial: 'sign', locals: {type: 'danger', text: @alias.errors.full_messages.to_sentence }%>
<% end %>
<%= render partial: 'panelstart', locals: {title: 'New Alias', type: "success" }%>
<%= form_for :alias, url: aliases_path do |a| %>
<tr>
    <td><%= a.label :uid, class: "sr-only" %></td>
    <td><%= a.text_field :uid, class: "form-control", placeholder: "Alias", required: true %></td>
</tr>
<tr>
   <td><%= a.label :forwardTo %></td>
   <td><%= a.select :forwardTo, options_for_select(Account.all.collect {|account| [account.uid]}), { include_hidden: false }, :multiple => false, class: "form-control", required: true %></td>
</tr>
<%= render partial: 'panelend'%>
<%= a.submit value: "Add Alias", class: "btn btn-lg btn-primary btn-success" %>
<% end %>