config/routes.rb
Rails.application.routes.draw do
    resources :accounts, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
        get :password, :on => :member
        patch :password, :on => :member, :action => :passwordupdate
    end
    resources :groups do
        get :delete, :on => :member
    end

    resources :aliases, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
    end

    resource :profile do
        get :password
        patch :password, :action => :passwordupdate
        get 'group/:id' => 'profiles#group', as: 'group'
        get 'group/:id/leave' => 'profiles#groupleave', as: 'groupleave'
        delete 'group/:id/leave' => 'profiles#groupleft', as: 'groupleft'
    end

    get '/', :to => 'profiles#index'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

end

app/models/group.rb
class Group < ActiveLdap::Base
  ldap_mapping dn_attribute: "cn",
               prefix: "ou=Groups",
               classes: ["groupOfNames"]
  has_many :members, :class_name => "Account",
      :wrap => "member", :primary_key => "dn"
  validates :cn, presence: true, format: { with: /\A[[:alnum:]]+\z/i }
  #validates :description, presence: true
  validates :members, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_filter :authorizeadmin

    def index
        @groups = Group.all(:limit => 50, :offset => params[:count].to_i, :sort_by => 'cn', :attributes => ["+", "*"])
    end

    def edit
        @group = Group.find(params[:id])
    end

    def new
        @group = Group.new
    end

    def create
        @group = Group.new(group_params[:cn])
        manage(@group)
    end

    def update
        @group = Group.find(group_params[:cn])
        manage(@group)
    end

    def show
        @group = Group.find(params[:id], :attributes => ["+", "*"])
        render 'group'
    end

    def destroy
        @group = Group.find(params[:id])
        @group.destroy
        redirect_to groups_path, notice: "Group deleted."
    end

    def delete
        @group = Group.find(params[:id])
    end

    private
    def group_params
        params.require(:group).permit(:cn, :description, :members => [])
    end
    def manage(group)
        group.description = group_params[:description]
        group.members.each { |m| group.members.delete(Account.find(m.uid)) }
        group_params[:members].each do |member| group.members.push(Account.find(member)) end
        begin
            if group.save
                redirect_to group
            else
                render 'edit'
            end
        rescue ActiveLdap::LdapError::InsufficientAccess
            redirect_to groups_path, alert: "Insufficient Access!" and return
        end
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/delete.html.erb
<%= form_for(@group, :url => { :action => :destroy }, :html => { :method => :delete }) do |f| %>
    <%= render partial: 'sign', locals: {type: 'danger', text: "Are you sure you want to delete the group '#{@group.cn}'?" } %>
    <%= link_to 'No', :back, class: "btn btn-lg btn-primary" %>
    <%= f.submit value: "Yes »", class: "btn btn-lg btn-danger" %>
<% end %>

app/views/groups/edit.html.erb
<% if @group.errors.any? %>
    <%= render partial: 'sign', locals: {type: 'danger', text: @group.errors.full_messages.to_sentence }%>
<% end %>
<%= render partial: 'panelstart', locals: {title: @group.dn, type: "info" }%>
<%= form_for :group, url: group_path(@group.dn), method: :patch do |g| %>
<tr>
   <td><%= g.label :cn %></td>
   <td><%= @group.cn %><%= g.hidden_field :cn, :value => @group.cn %></td>
</tr>
<tr>
   <td><%= g.label :description %></td>
   <td><%= g.text_field :description, class: "form-control", placeholder: "Group Description" %></td>
</tr>
<tr>
   <td><%= g.label :members %></td>
   <td><%= g.select :members, options_for_select(Account.all.collect {|account| [account.uid]}, @group.members.collect {|member| member.uid}), { include_hidden: false }, :multiple => true, class: "form-control", required: true %></td>
</tr>
<%= render partial: 'panelend'%>
<%= g.submit value: "Update Group", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/groups/index.html.erb
<table class="table table-striped">
<tr>
    <th>Groupname</th>
    <th>Group Description</th>
    <th>Members</th>
</tr>
<% @groups.each do |g| %>
    <tr>
    <td><%= link_to g.cn, group_path(g.dn), title: g.dn %></td>
    <td><%= g.description %></td>
    <td><% g.members.each do |a| %> <%= link_to a.uid, account_path(a.dn), title: a.dn %><% end %></td>
    </tr>
<% end %>
</table>
<%= link_to 'New Group', new_group_path, class: "btn btn-lg btn-primary btn-success" %>
<% if params[:count].to_i > 50 %>
    <%= link_to 'Previous 50', groups_path(:count => params[:count].to_i-50), class: "btn btn-lg btn-primary" %>
<% end %>
<% if @groups.length == 50 %>
<%= link_to 'Next 50', groups_path(:count => params[:count].to_i+50), class: "btn btn-lg btn-primary" %>
<% end %>

app/views/groups/new.html.erb
<% if @group.errors.any? %>
    <%= render partial: 'sign', locals: {type: 'danger', text: @group.errors.full_messages.to_sentence }%>
<% end %>
<%= render partial: 'panelstart', locals: {title: 'New Group', type: "success" }%>
<%= form_for :group, url: groups_path do |g| %>
<tr>
    <td><%= g.label :cn %></td>
    <td><%= g.text_field :cn, class: "form-control", placeholder: "Groupname", required: true %></td>
</tr>
<tr>
    <td><%= g.label :description %></td>
    <td><%= g.text_field :description, class: "form-control", placeholder: "Group Description" %></td>
</tr>
<tr>
    <td><%= g.label :members %></td>
    <td><%= g.select :members, Account.all.collect {|account| [account.uid]}, { include_hidden: false }, :multiple => true, class: "form-control", required: true %></td>
</tr>
<%= render partial: 'panelend'%>
<%= g.submit value: "Add Group", class: "btn btn-lg btn-primary btn-success" %>
<% end %>