config/routes.rb
Rails.application.routes.draw do
    resources :accounts, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
        get :password, :on => :member
        patch :password, :on => :member, :action => :passwordupdate
    end
    resources :groups do
        get :delete, :on => :member
    end

    resources :aliases, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
    end

    resource :profile do
        get :password
        patch :password, :action => :passwordupdate
        get 'group/:id' => 'profiles#group', as: 'group'
        get 'group/:id/leave' => 'profiles#groupleave', as: 'groupleave'
        delete 'group/:id/leave' => 'profiles#groupleft', as: 'groupleft'
    end

    get '/', :to => 'profiles#index'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    class PasswordMismatch < StandardError
    end
    class PasswordEmpty < StandardError
    end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
      begin
          @current_user ||= Account.find(session[:uid]) if session[:uid]
      rescue ActiveLdap::ConnectionNotSetup 
          @current_user = false
      rescue ActiveLdap::EntryNotFound
          redirect_to '/logout'
      end
  end
  helper_method :current_user

  def authorize
      redirect_to '/login' unless current_user
  end

  def current_user_admin
      @current_user_admin = false
      if current_user
          begin
              current_user.groups.each do |group| 
                  @current_user_admin = true if group.dn == 'cn=hrpeople,ou=Groups,'+Rails.application.config.ldapbase
              end
          rescue ActiveLdap::ConnectionNotSetup
          end
      end
      return @current_user_admin
  end
  helper_method :current_user_admin

  def authorizeadmin
      not_found unless current_user_admin
  end

  def not_found
      redirect_to '/logout'
        #raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      css_class = column == sort_column ? "current #{sort_direction}" : nil
      direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
      link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/views/application/_panelend.html.erb
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>

app/views/application/_panelstart.html.erb
<div class="panel panel-<%= type %>">
<div class="panel-heading">
    <h3 class="panel-title"> <%= title %> </h3>
</div>
<div class="panel-body">
    <div class="row">
        <div class=" col-md-9 col-lg-9 ">
            <table class="table table-user-information">
                <tbody>

app/views/application/_sign.html.erb
<div class="span4">
<div class="alert alert-<%= type %>">
    <strong><%= text %></strong>
</div>
</div>

app/views/application/account.html.erb
<% if current_user_admin %>
<%= render partial: 'panelstart', locals: {title: @account.dn, type: "info" }%>
<% else %>
<%= render partial: 'panelstart', locals: {title: @account.uid, type: "info" }%>
<% end %>
<tr>
    <td>Account</td>
    <td><%= @account.uid %></td>
</tr>
<tr>
    <td>Groups</td>
    <td><% @account.groups.each do |g| %>
        <% if current_user_admin %>
            <%= link_to g.cn, group_path(g), title: g.description %>
        <% else %>
            <%= link_to g.cn, group_profile_path(g), title: g.description %>
        <% end %>
    <% end %></td>
</tr>
<% if current_user_admin %>
<tr>
    <td>creatorsName</td>
    <td><%= @account.creatorsName %></td>
</tr>
<tr>
    <td>createTimestamp</td>
    <td><%= @account.createTimestamp %></td>
</tr>
<tr>
    <td>authTimestamp</td>
    <td><%= @account.authTimestamp %></td>
</tr>
<tr>
    <td>pwdChangedTime</td>
    <td><%= (@account.respond_to? :pwdChangedTime) ? @account.pwdChangedTime : "<b>BAD USR NEVAR CHANGED PAZZWORDZ!!111!</b>".html_safe %></td<>
</tr>
<tr>
    <td>modifiersName</td>
    <td><%= @account.modifiersName %></td>
</tr>
<tr>
    <td>modifyTimestamp</td>
    <td><%= @account.modifyTimestamp %></td>
</tr>
<% end %>
<%= render partial: 'panelend'%>
<% if current_user_admin %>
<%= link_to 'Change Password', password_account_path(@account.dn), class: "btn btn-lg btn-primary" %>
<%= link_to 'Edit Account', edit_account_path(@account.dn), class: "btn btn-lg btn-primary" %>
<%= link_to 'Delete Account', delete_account_path(@account.dn), method: :delete, class: "btn btn-lg btn-danger", data: { confirm: 'Are you sure?' } %>
<% else %>
<%= link_to 'Change Password', password_profile_path, class: "btn btn-lg btn-primary" %>
<% end %>

app/views/application/alias.html.erb
<% if current_user_admin %>
<%= render partial: 'panelstart', locals: {title: @alias.dn, type: "info" }%>
<% else %>
<%= render partial: 'panelstart', locals: {title: @alias.uid, type: "info" }%>
<% end %>
<tr>
    <td>Alias</td>
    <td><%= @alias.uid %></td>
</tr>
<tr>
    <td>ForwardTo</td>
    <td><%= @alias.forwardTo %></td>
</tr>
<% if current_user_admin %>
<tr>
    <td>creatorsName</td>
    <td><%= @alias.creatorsName %></td>
</tr>
<tr>
    <td>createTimestamp</td>
    <td><%= @alias.createTimestamp %></td>
</tr>
<tr>
    <td>modifiersName</td>
    <td><%= @alias.modifiersName %></td>
</tr>
<tr>
    <td>modifyTimestamp</td>
    <td><%= @alias.modifyTimestamp %></td>
</tr>
<% end %>
<%= render partial: 'panelend'%>
<% if current_user_admin %>
<%= link_to 'Edit Alias', edit_alias_path(@alias), class: "btn btn-lg btn-primary" %>
<%= link_to 'Delete Alias', delete_alias_path(@alias), method: :delete, class: "btn btn-lg btn-danger", data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/application/group.html.erb
<% if current_user_admin %>
<%= render partial: 'panelstart', locals: {title: @group.dn, type: "info" }%>
<% else %>
<%= render partial: 'panelstart', locals: {title: @group.cn, type: "info" }%>
<% end %>
<tr>
    <td>Group</td>
    <td><%= @group.cn %></td>
</tr>
<tr>
    <td>Description</td>
    <td><%= @group.description %></td>
</tr>
<% if current_user_admin %>
<tr>
    <td>creatorsName</td>
    <td><%= @group.creatorsName %></td>
</tr>
<tr>
    <td>createTimestamp</td>
    <td><%= @group.createTimestamp %></td>
</tr>
<tr>
    <td>members</td>
    <td><% @group.members.each do |a| %> <%= link_to a.uid, account_path(a.dn), title: a.dn %><% end %></td>
</tr>
<% end %>
<%= render partial: 'panelend'%>
<% if current_user_admin %>
<%= link_to 'Edit Group', edit_group_path(@group.cn), class: "btn btn-lg btn-primary" %>
<%= link_to 'Delete Group', delete_group_path(@group.cn), method: :delete, class: "btn btn-lg btn-danger", data: { confirm: 'Are you sure?' } %>
<% else %>
    <%= link_to 'Leave Group', groupleave_profile_path(@group.cn), class: "btn btn-lg btn-danger" %>
<% end %>