config/routes.rb
Rails.application.routes.draw do
    resources :accounts, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
        get :password, :on => :member
        patch :password, :on => :member, :action => :passwordupdate
    end
    resources :groups do
        get :delete, :on => :member
    end

    resources :aliases, constraints: { id: /[a-zA-Z1-9\.@,\=]+/ } do
        get :delete, :on => :member
    end

    resource :profile do
        get :password
        patch :password, :action => :passwordupdate
        get 'group/:id' => 'profiles#group', as: 'group'
        get 'group/:id/leave' => 'profiles#groupleave', as: 'groupleave'
        delete 'group/:id/leave' => 'profiles#groupleft', as: 'groupleft'
    end

    get '/', :to => 'profiles#index'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

end

app/models/account.rb
class Account < ActiveLdap::Base
  ldap_mapping dn_attribute: "uid",
               prefix: "ou=Accounts",
               classes: ["c44Account", "simpleSecurityObject", "scrambler"],
               scope: :sub
  belongs_to :groups, :class_name => "Group",
      :many => "member", :foreign_key => "dn"
  validates :uid, presence: true, :format => {:with => /\A[[:alnum:].-]+@(ourdomain.tld|anotherdomain.tld)\z/i }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_filter :authorizeadmin

    def index
        @accounts = Account.all(:limit => 50, :offset => params[:count].to_i, :sort_by => 'uid', :attributes => ["+", "*"])
    end

    def new
        @account = Account.new
    end

    def create
        @account = Account.new(account_params)
        @account.userPassword = mkpassword(params[:account][:userpassword], params[:account][:userpassword_confirmation])
        begin
            if @account.save
                redirect_to @account
            else
                render 'new'
            end
        rescue ActiveLdap::LdapError::InsufficientAccess
            redirect_to accounts_path, alert: "Insufficient Access!"
        rescue ActiveLdap::LdapError::ConstraintViolation
            redirect_to accounts_path, alert: "Account UIDs must be #{UIDCONST} and unique"
        end
    end

    def show
        begin
            @account = Account.find(params[:id], :attributes => ["+", "*"])
        rescue ActiveLdap::EntryNotFound
            redirect_to accounts_path, alert: "Account #{params[:id]} not found." and return
        end
        render 'account'
    end

    def edit
        @account = Account.find(params[:id])
    end

    def update
        account = Account.find(account_params[:uid])
        account.openPGPpublicKey = account_params[:openPGPpublicKey]
        account.sshRSAAuthKey = account_params[:sshRSAAuthKey]
        account.sshED25519AuthKey = account_params[:sshED25519AuthKey]
        begin
            account.save
            redirect_to account_path(params[:account][:uid]), notice: "Account #{account.uid} updated."
        rescue ActiveLdap::LdapError::InsufficientAccess
            redirect_to account_path(params[:account][:uid]), alert: "Insufficient Access!"
        end
    end

    def destroy
        Account.destroy(params[:id])
        redirect_to accounts_path, notice: "Account #{params[:id]} deleted."
    end

    def password
        session[:return_to] ||= request.referer
        begin
            @account = Account.find(params[:id], :attributes => ["+", "*"])
        rescue ActiveLdap::EntryNotFound
            redirect_to accounts_path, notice: "Account not found."
        end
    end

    def passwordupdate
        begin
            raise PasswordMismatch if params[:account][:userpassword] != params[:account][:userpassword_confirmation]
            raise PasswordEmpty if params[:account][:userpassword].empty?
            @account = Account.find(params[:account][:uid])
            salt = "$6$#{ActiveLdap::UserPassword::Salt.generate(22)}"
            @account.userPassword = ActiveLdap::UserPassword.crypt(params[:account][:userpassword], salt)
            @account.save
            redirect_to session.delete(:return_to), notice: "Password changed." and return
        rescue AccountsController::PasswordEmpty
            redirect_to session.delete(:return_to), alert: "Password mut not be empty!" and return
        rescue AccountsController::PasswordMismatch
            redirect_to session.delete(:return_to), alert: "Password Mismatch!" and return
        rescue ActiveLdap::LdapError::InsufficientAccess
            redirect_to session.delete(:return_to), alert: 'Password could not be changed.' and return
        end
    end

    def delete
        @account = Account.find(params[:id])
    end

    protected
    def mkpassword(password, password_confirmation)
        raise PasswordMismatch if password != password_confirmation
        raise PasswordEmpty if password.empty?
        salt = "$6$#{ActiveLdap::UserPassword::Salt.generate(22)}"
        password = ActiveLdap::UserPassword.crypt(password, salt)
        password
    end

    private
    def account_params
        params.require(:account).permit(:uid, :userpassword, :openPGPpublicKey, :sshRSAAuthKey, :sshED25519AuthKey)
    end

    def initscrambler(password)
        iterations = 12
        blowfishscheme = '$2a$'
        salt = Base64.strict_encode64(random.bytes(16)).gsub('+', '.').slice 0, 22
        settings = "#{blowfishscheme}#{iterations}$#{salt}"
        hashed_password = BCrypt::Engine.hash_secret password, settings
        @key_pair = OpenSSL::PKey::RSA.new 2048
        @key_pair.to_pem(OpenSSL::Cipher.new('aes-256-cbc'), hashed_password).gsub /\n/, '_'
    end



end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/delete.html.erb
<%= form_for(@account, :url => { :action => :destroy }, :html => { :method => :delete }) do |f| %>
    <%= render partial: 'sign', locals: {type: 'danger', text: "Are you sure you want to delete the account '#{@account.uid}'?" } %>
    <%= link_to 'No', :back, class: "btn btn-lg btn-primary" %>
    <%= f.submit value: "Yes »", class: "btn btn-lg btn-danger" %>
<% end %>

app/views/accounts/edit.html.erb
<%= render partial: 'panelstart', locals: {title: @account.dn, type: "info" }%>
<%= form_for :account, url: account_path, method: :patch do |a| %>
<tr>
    <td><%= a.label :uid %></td>
    <td><%= @account.uid %><%= a.hidden_field :uid, :value => @account.uid %></td>
</tr>
<tr>
    <td><%= a.label :openPGPpublicKey %></td>
    <td><%= a.text_area :openPGPpublicKey, class: "form-control", placeholder: "openPGPpublicKey", :cols => "60", :rows => "10" %></td>
</tr>
<tr>
    <td><%= a.label :sshRSAAuthKey %></td>
    <td><%= a.text_area :sshRSAAuthKey, class: "form-control", placeholder: "ssh-rsa ..."%></td>
</tr>
<tr>
    <td><%= a.label :sshED25519AuthKey %></td>
    <td><%= a.text_field :sshED25519AuthKey, class: "form-control", placeholder: "ssh-ed25519 ..."%></td>
</tr>
<tr>
    <td><%= a.label :scramblerPublicKey %></td>
    <td><%= a.text_area :scramblerPublicKey, class: "form-control", :readonly => true%></td>
</tr>
<tr>
    <td><%= a.label :scramblerPrivateKey %></td>
    <td><%= a.text_area :scramblerPrivateKey, class: "form-control", :readonly => true%></td>
</tr>
<%= render partial: 'panelend'%>
<%= a.submit value: "Update Account", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/accounts/index.html.erb
<table class="table table-striped">
<tr>
    <th>UID</th>
    <th>Created</th>
    <th>Last modified</th>
</tr>
<% @accounts.each do |account| %>
    <tr>
    <td><%= link_to account.uid, account_path(account.dn), title: account.dn %></td>
    <td><%= account.createTimestamp %></td>
    <td><%= account.modifyTimestamp %></td>
    </tr>
<% end %>
</table>
<%= link_to 'New Account', new_account_path, class: "btn btn-lg btn-primary btn-success" %>

app/views/accounts/new.html.erb
<% if @account.errors.any? %>
    <%= render partial: 'sign', locals: {type: 'danger', text: @account.errors.full_messages.to_sentence }%>
<% end %>
<%= render partial: 'panelstart', locals: {title: 'New Account', type: "success" }%>
<%= form_for :account, url: accounts_path do |a| %>
<tr>
    <td><%= a.label :uid, class: "sr-only" %></td>
    <td><%= a.text_field :uid, class: "form-control", placeholder: "Accountid", required: true %></td>
</tr>
<tr>
    <td><%= a.label :userpassword, class: "sr-only" %></td>
    <td><%= a.password_field :userpassword, class: "form-control", placeholder: "Password", required: true %></td>
</tr>
<tr>
    <td><%= a.label :userpassword_confirmation, class: "sr-only" %></td>
    <td><%= a.password_field :userpassword_confirmation, class: "form-control", placeholder: "Repeat password", required: true %></td>
</tr>
<%= render partial: 'panelend'%>
<%= a.submit value: "Add Account", class: "btn btn-lg btn-primary btn-success" %>
<% end %>

app/views/accounts/password.html.erb
<%= render partial: 'sign', locals: {type: 'warning', text: "Change password for '#{@account.dn}':" } %>
<%= form_for @account, url: password_account_path, html: { class: "col-sm-6 col-sm-offset-3" }  do |f| %>
    <%= f.hidden_field :uid, :value => @account.uid %>
    <%= f.label :userpassword, class: "sr-only" %>
    <%= f.password_field :userpassword, class: "form-control", placeholder: "Password", required: true %>
    <%= f.label :userpassword_confirmation, class: "sr-only" %>
    <%= f.password_field :userpassword_confirmation, class: "form-control", placeholder: "Repeat password", required: true %>
    <%= f.submit value: "Change Password", class: "btn btn-lg btn-primary btn-block" %>
<% end %>